export const TUTORIAL_STEPS = Object.freeze([
  {
    id: "farmer_intro",
    speaker: "farmer",
    selectRole: "farmer",
    faceDown: true,
    focusRole: false,
    text: "Welcome to Cleared to Build. This is a base-building strategy game where your choices shape how the run turns out.",
  },
  {
    id: "farmer_choices",
    speaker: "farmer",
    text: "You decide when to expand, what to build, what to gather, and how prepared your town is when danger shows up.",
  },
  {
    id: "top_bar",
    speaker: "farmer",
    highlight: "topHud",
    text: "The top bar tracks the resources that keep your town alive.",
  },
  {
    id: "top_bar_needs",
    speaker: "farmer",
    highlight: "topHud",
    text: "Your people eat Food and drink Water to stay active. Seeds let you plant and grow food. Berries energize and heal your players.",
  },
  {
    id: "top_bar_supplies",
    speaker: "farmer",
    highlight: "topHud",
    text: "Wood and Stone builds your town. Growth Permits buy contracts. Money lets you recruit and pay for key purchases.",
  },
  {
    id: "tabs_intro",
    speaker: "farmer",
    openTab: "functions",
    highlight: "bottomTabs",
    speechPlacement: "top",
    text: "The bottom bar is split into tabs. The Functions tab lets you control and order your town and crew in different ways.",
  },
  {
    id: "tabs_store",
    speaker: "farmer",
    openTab: "functions",
    highlight: "bottomTabs",
    speechPlacement: "top",
    text: "The Store tab is where you purchase buildings and troops.",
  },
  {
    id: "tabs_facilities",
    speaker: "farmer",
    openTab: "functions",
    highlight: "bottomTabs",
    speechPlacement: "top",
    text: "The Clay Ovens tab, Storage tab, and Houses tab let you inspect those facilities directly. The Cards tab is where you access your deck cards and consumable powerup cards.",
  },
  {
    id: "farm_mode",
    speaker: "farmer",
    openTab: "functions",
    highlight: "farmButton",
    speechPlacement: "top",
    waitFor: { action: "function.mode", mode: "Farm" },
    allowedActions: [{ action: "function.mode", mode: "Farm" }],
    resumeSimulation: true,
    text: "Start in the Functions tab. Press Farm.",
  },
  {
    id: "farm_plots",
    speaker: "farmer",
    waitFor: { action: "farm.planted" },
    resumeSimulation: true,
    text: "Now place a small farm plot on grass tiles and confirm it. Your Farmers will till it and plant it for you.",
  },
  {
    id: "forager_intro",
    speaker: "forager",
    selectRole: "forager",
    text: "I'm the Forager. I work outside town, gather resources from parcels, and bring those supplies back home.",
  },
  {
    id: "forager_supply_line",
    speaker: "forager",
    text: "That keeps the rest of the town growing.",
  },
  {
    id: "forest_contract_slot",
    speaker: "forager",
    forceDetailed: true,
    focusParcel: "E",
    hoverParcel: "E",
    highlight: "eastContractHud",
    speechPlacement: "contractBottom",
    waitFor: { action: "contractHud.slot", slotId: "E" },
    allowedActions: [{ action: "contractHud.slot", slotId: "E" }],
    resumeSimulation: true,
    text: "Expansion starts with contracts. Click the East parcel to open its contract page.",
  },
  {
    id: "contract_types_intro",
    speaker: "forager",
    highlight: "contractForestButton",
    speechPlacement: "contractBottom",
    allowedActions: [{ action: "contractHud.slot", slotId: "E" }],
    text: "Each contract helps in a different way. Forest gives Wood. Rock gives Stone and some Gold.",
  },
  {
    id: "contract_types_field_market",
    speaker: "forager",
    highlight: "contractFarmButton",
    speechPlacement: "contractBottom",
    allowedActions: [{ action: "contractHud.slot", slotId: "E" }],
    text: "Field contracts supply Seeds and Berries. The Market lets you buy supplies.",
  },
  {
    id: "contract_types_pressure",
    speaker: "forager",
    highlight: "contractPressureButton",
    speechPlacement: "contractBottom",
    allowedActions: [{ action: "contractHud.slot", slotId: "E" }],
    text: "Pressure is a combat contract. It lets you fight enemies and rewards you with Money and XP for defeating them.",
  },
  {
    id: "forest_contract_buy",
    speaker: "forager",
    highlight: "contractForestButton",
    speechPlacement: "contractBottom",
    waitFor: { action: "parcel.commit", slotId: "E", type: "FOREST", source: "contractHud" },
    allowedActions: [
      { action: "contractHud.slot", slotId: "E" },
      { action: "contractHud.type", slotId: "E", type: "FOREST" },
      { action: "parcel.commit", slotId: "E", type: "FOREST", source: "contractHud" },
    ],
    resumeSimulation: true,
    text: "Buy the Forest contract first. It is a simple way to start building up your supply line.",
  },
  {
    id: "route_forager",
    speaker: "forager",
    selectRole: "forager",
    waitFor: { action: "forager.route", resourceType: "wood" },
    resumeSimulation: true,
    text: "With me selected already, click a tree in the new parcel so I can go gather wood from it.",
  },
  {
    id: "builder_intro",
    speaker: "builder",
    selectRole: "builder",
    openTab: "build",
    setBuildMode: "buildings",
    speechPlacement: "top",
    text: "I'm the Builder. I turn your resources into structures and keep those structures standing.",
  },
  {
    id: "builder_damage",
    speaker: "builder",
    openTab: "build",
    setBuildMode: "buildings",
    speechPlacement: "top",
    text: "That matters when the town takes damage.",
  },
  {
    id: "build_house",
    speaker: "builder",
    openTab: "build",
    setBuildMode: "buildings",
    highlight: "buildHouseCard",
    speechPlacement: "top",
    ensureMaterials: { wood: 8, stone: 4, permits: 1 },
    waitFor: { action: "build.placed", key: "house" },
    allowedActions: [
      { action: "build.select", key: "house" },
      { action: "build.placed", key: "house" },
    ],
    resumeSimulation: true,
    text: "Place a House first.",
  },
  {
    id: "house_info",
    speaker: "builder",
    openTab: "build",
    setBuildMode: "buildings",
    highlight: "buildHouseCard",
    speechPlacement: "top",
    text: "Each House supports two players, so this one gives you room for two more crew members.",
  },
  {
    id: "build_storage",
    speaker: "builder",
    openTab: "build",
    setBuildMode: "buildings",
    highlight: "buildStorageCard",
    speechPlacement: "top",
    ensureMaterials: { wood: 4 },
    waitFor: { action: "build.placed", key: "storage" },
    allowedActions: [
      { action: "build.select", key: "storage" },
      { action: "build.placed", key: "storage" },
    ],
    resumeSimulation: true,
    text: "Now place a Storage building.",
  },
  {
    id: "storage_info",
    speaker: "builder",
    openTab: "build",
    setBuildMode: "buildings",
    highlight: "buildStorageCard",
    speechPlacement: "top",
    text: "Storage gives you more room to hold what the town brings in. If you cannot hold supplies, the whole town slows down.",
  },
  {
    id: "fireman_intro",
    speaker: "fireman",
    selectRole: "fireman",
    openTab: "functions",
    highlight: "waterButton",
    speechPlacement: "top",
    text: "I'm the Fireman. I run ovens and produce water for the town.",
  },
  {
    id: "water_on",
    speaker: "fireman",
    openTab: "functions",
    highlight: "waterButton",
    speechPlacement: "top",
    setWaterDraft: 1,
    waitFor: { action: "function.water", enabled: true, target: 1 },
    allowedActions: [{ action: "function.water", enabled: true, target: 1 }],
    resumeSimulation: true,
    text: "Start Water production of 1 Water.",
  },
  {
    id: "brawler_intro",
    speaker: "brawler",
    text: "I'm one of the fighters. I defend the town when raiders show up and help keep your people alive through the night.",
  },
  {
    id: "buy_brawler",
    speaker: "brawler",
    openTab: "build",
    setBuildMode: "units",
    highlight: "buildUnitStoreArea",
    speechPlacement: "top",
    waitFor: { action: "build.recruit", key: "brawler" },
    allowedActions: [{ action: "build.recruit", key: "brawler" }],
    resumeSimulation: true,
    text: "Recruit one Brawler from the Troops section.",
  },
  {
    id: "core_loop",
    speaker: "farmer",
    selectRole: "farmer",
    text: "That is the core loop. Grow food, gather resources, build your town, produce water, and recruit help.",
  },
  {
    id: "core_loop_defend",
    speaker: "farmer",
    text: "Your first night is free: no raiders tonight. After that, defend the night, then expand again.",
  },
  {
    id: "town_towers",
    speaker: "farmer",
    forceDetailed: true,
    highlightTownTower: true,
    text: "One more thing: Town Towers are the heartbeat of your town.",
  },
  {
    id: "town_towers_rewards",
    speaker: "farmer",
    forceDetailed: true,
    highlightTownTower: true,
    text: "Each one gives you money and 1 expansion permit at dawn, so towns that keep building them usually keep growing.",
  },
  {
    id: "finish",
    speaker: "farmer",
    selectRole: "farmer",
    completeOnAdvance: true,
    text: "Awesome, now you're ready to take on the game. Saving is now enabled.",
  },
]);
