export const TUTORIAL_STEPS = Object.freeze([
  {
    id: "farmer_intro",
    speaker: "farmer",
    selectRole: "farmer",
    faceDown: true,
    focusRole: false,
    text: "Welcome to Permit Approved! This is a base-building strategy game where your choices shape how the run turns out.",
  },
  {
    id: "farmer_choices",
    speaker: "farmer",
    text: "Each day gives you time to grow, gather, build, and prepare.",
  },
  {
    id: "farmer_goal",
    speaker: "farmer",
    text: "Keep one goal in mind: reach Sunday night, then defeat The Shocker to beat the game.",
  },
  {
    id: "top_bar",
    speaker: "farmer",
    highlight: "topHud",
    text: "The top bar tracks the resources that keep your town alive.",
  },
  {
    id: "top_bar_needs",
    speaker: "farmer",
    highlight: "topHud",
    text: "Food and Water keep your townfolk alive and active. Seeds grow more food. Berries can heal and energize your players.",
  },
  {
    id: "top_bar_supplies",
    speaker: "farmer",
    highlight: "topHud",
    text: "Wood and Stone are what builds up your town. Growth Permits buy contracts. Money helps you recruit and make key purchases.",
  },
  {
    id: "tabs_intro",
    speaker: "farmer",
    openTab: "functions",
    highlight: "bottomTabs",
    speechPlacement: "top",
    text: "The bottom bar is split into tabs. This is where most town decisions happen.",
  },
  {
    id: "farm_mode",
    speaker: "farmer",
    openTab: "functions",
    highlight: "farmButton",
    speechPlacement: "top",
    waitFor: { action: "function.mode", mode: "Farm" },
    allowedActions: [{ action: "function.mode", mode: "Farm" }],
    resumeSimulation: true,
    text: "Let's start with farming. Press Farm.",
  },
  {
    id: "farm_plots",
    speaker: "farmer",
    waitFor: { action: "farm.planted" },
    resumeSimulation: true,
    text: "Now place a small farm plot on grass tiles and confirm it. Put it near the Storage building if you can: the closer bthe better.",
  },
  {
    id: "forager_intro",
    speaker: "forager",
    selectRole: "forager",
    text: "Hey, I'm the Forager. If there's something useful outside town, I'm probably already looking for it.",
  },
  {
    id: "forager_supply_line",
    speaker: "forager",
    text: "I work outside town, gather resources from parcels, and bring those supplies back home.",
  },
  {
    id: "forest_contract_slot",
    speaker: "forager",
    forceDetailed: true,
    focusParcel: "E",
    hoverParcel: "E",
    highlight: "eastContractHud",
    speechPlacement: "contractBottom",
    waitFor: { action: "contractHud.slot", slotId: "E" },
    allowedActions: [{ action: "contractHud.slot", slotId: "E" }],
    resumeSimulation: true,
    tutorialArrow: "eastContractHud",
    text: "Expansion starts with contracts. Click the East contract button to open the contract page for that side of town.",
  },
  {
    id: "contract_types_intro",
    speaker: "forager",
    highlight: "contractForestButton",
    speechPlacement: "contractBottom",
    allowedActions: [{ action: "contractHud.slot", slotId: "E" }],
    text: "Each contract helps in a different way. The Forest contract gives Wood. The Rock contract grants you Stone and some Gold ores for extra money.",
  },
  {
    id: "contract_types_field_market",
    speaker: "forager",
    highlight: "contractFarmButton",
    speechPlacement: "contractBottom",
    allowedActions: [{ action: "contractHud.slot", slotId: "E" }],
    text: "Field contracts supply Seeds for growing more Food, plus Berries for quick Stamina and Health boosts to troops. The Market lets you buy supplies when you need something fast.",
  },
  {
    id: "contract_types_pressure",
    speaker: "forager",
    highlight: "contractPressureButton",
    speechPlacement: "contractBottom",
    allowedActions: [{ action: "contractHud.slot", slotId: "E" }],
    text: "The Pressure contract is combat-based. You fight enemies there for Money and XP, so make sure you have a fighter in town before buying one.",
  },
  {
    id: "forest_contract_buy",
    speaker: "forager",
    highlight: "contractForestButton",
    speechPlacement: "contractBottom",
    waitFor: { action: "parcel.commit", slotId: "E", type: "FOREST", source: "contractHud" },
    allowedActions: [
      { action: "contractHud.slot", slotId: "E" },
      { action: "contractHud.type", slotId: "E", type: "FOREST" },
      { action: "parcel.commit", slotId: "E", type: "FOREST", source: "contractHud" },
    ],
    resumeSimulation: true,
    text: "Buy the Forest contract first. It is a simple way to start building up your supply line.",
  },
  {
    id: "route_forager",
    speaker: "forager",
    selectRole: "forager",
    waitFor: { action: "forager.route", resourceType: "wood" },
    resumeSimulation: true,
    text: "With me selected already, click a tree in the new parcel so I can go gather wood from it.",
  },
  {
    id: "builder_intro",
    speaker: "builder",
    selectRole: "builder",
    openTab: "build",
    setBuildMode: "buildings",
    speechPlacement: "top",
    text: "Builder here. Give me supplies and a little space, and I'll turn this place into something that lasts.",
  },
  {
    id: "build_house",
    speaker: "builder",
    openTab: "build",
    setBuildMode: "buildings",
    highlight: "buildHouseCard",
    speechPlacement: "top",
    ensureMaterials: { wood: 8, stone: 4, permits: 1 },
    waitFor: { action: "build.placed", key: "house" },
    allowedActions: [
      { action: "build.select", key: "house" },
      { action: "build.placed", key: "house" },
    ],
    resumeSimulation: true,
    text: "Let's place a House first so we can recruit more members. Try to keep new buildings near the town.",
  },
  {
    id: "house_info",
    speaker: "builder",
    openTab: "build",
    setBuildMode: "buildings",
    highlight: "buildHouseCard",
    speechPlacement: "top",
    text: "Each House supports two players, so this one gives you room for two more crew members.",
  },
  {
    id: "build_storage",
    speaker: "builder",
    openTab: "build",
    setBuildMode: "buildings",
    highlight: "buildStorageCard",
    speechPlacement: "top",
    ensureMaterials: { wood: 4 },
    waitFor: { action: "build.placed", key: "storage" },
    allowedActions: [
      { action: "build.select", key: "storage" },
      { action: "build.placed", key: "storage" },
    ],
    resumeSimulation: true,
    text: "Now place a Storage building near the town so your workers have a shorter trip.",
  },
  {
    id: "storage_info",
    speaker: "builder",
    openTab: "build",
    setBuildMode: "buildings",
    highlight: "buildStorageCard",
    speechPlacement: "top",
    text: "Storages give you more room to hold what the town brings in. If your storages are filled to the brim, the whole town slows down.",
  },
  {
    id: "fireman_intro",
    speaker: "fireman",
    selectRole: "fireman",
    openTab: "functions",
    highlight: "waterButton",
    speechPlacement: "top",
    text: "Fireman reporting in. I keep clean water moving, even when everyone suddenly remembers they're thirsty.",
  },
  {
    id: "water_on",
    speaker: "fireman",
    openTab: "functions",
    highlight: "waterButton",
    speechPlacement: "top",
    setWaterDraft: 1,
    waitFor: { action: "function.water", enabled: true, target: 1 },
    allowedActions: [{ action: "function.water", enabled: true, target: 1 }],
    resumeSimulation: true,
    text: "Start Water production of 1 Water.",
  },
  {
    id: "water_cost",
    speaker: "fireman",
    openTab: "functions",
    highlight: "waterButton",
    speechPlacement: "top",
    text: "To produce clean drinkable Water, I need 1 Unclean Water fetched from the shore and a piece of Wood to heat the process. Supply me with fuel and something to clean, and I'll handle the rest.",
  },
  {
    id: "brawler_intro",
    speaker: "brawler",
    text: "Brawler here. Point me at trouble and I'll keep it away from the town.",
  },
  {
    id: "buy_brawler",
    speaker: "brawler",
    openTab: "build",
    setBuildMode: "units",
    highlight: "buildUnitStoreArea",
    speechPlacement: "top",
    waitFor: { action: "build.recruit", key: "brawler" },
    allowedActions: [{ action: "build.recruit", key: "brawler" }],
    resumeSimulation: true,
    text: "Recruit one Brawler from the Troops section.",
  },
  {
    id: "core_loop",
    speaker: "farmer",
    selectRole: "farmer",
    text: "That is the core loop. Grow food, gather resources, build your town, produce water, and recruit help.",
  },
  {
    id: "core_loop_defend",
    speaker: "farmer",
    text: "Your first night is free: no raiders tonight. After that, waves of enemies will come for your town every night.",
  },
  {
    id: "town_towers",
    speaker: "farmer",
    forceDetailed: true,
    highlightTownTower: true,
    text: "One more thing: Town Towers are the heartbeat of your settlement.",
  },
  {
    id: "town_towers_rewards",
    speaker: "farmer",
    forceDetailed: true,
    highlightTownTower: true,
    text: "Each one gives you Money and 1 Growth Permit every day at dawn, so towns that keep building them usually keep growing.",
  },
  {
    id: "finish",
    speaker: "farmer",
    selectRole: "farmer",
    completeOnAdvance: true,
    text: "You're ready to go. Saving is now enabled.",
  },
]);
